#8 Install last version if restore didn't work

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -117,9 +117,17 @@ runs:
     #     dotnet tool restore
     #   shell: bash
 
-    - name: Install dotnet-stryker (local or global)
+    - name: Install dotnet-stryker (restore or install)
       run: |
         dotnet tool restore
+        dotnet tool list --local | grep dotnet-stryker > /dev/null
+        if [ $? -ne 0 ]; then
+            echo "Required tool 'dotnet-stryker' was not restored. Install last version"
+            echo "To optimize this step, install dotnet-stryker via manifest https://stryker-mutator.io/docs/stryker-net/getting-started/#install-in-project"
+            
+            dotnet tool install dotnet-stryker
+            dotnet tool restore
+        fi
       shell: bash
 
     - name: Report source branch
